apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-wind-wind-turbine-app-dev
  annotations:
    argocd/app-name: test-wind-wind-turbine-app-dev
    backstage.io/kubernetes-id: test-wind-wind-turbine-app
    backstage.io/kubernetes-namespace: test-wind
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: neenspa/test-wind-wind-turbine
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.democp.vega.local/dev-pipelines/ns/test-wind/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.democp.vega.local/k8s/ns/test-wind/deployments/test-wind-wind-turbine-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.democp.vega.local/#https://github.com/neenspa/test-wind-wind-turbine?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "daniele"
